############## NET - IOSTANDARD ##################
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
#############SPI Configurate Setting##################
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
############## clock and reset define##################
create_clock -period 20.000 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]
set_property PACKAGE_PIN P15 [get_ports sys_clk]

set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN AB2 [get_ports rst_n]
############## usb uart define########################
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx]
set_property PACKAGE_PIN B16 [get_ports uart_rx]

set_property IOSTANDARD LVCMOS33 [get_ports uart_tx]
set_property PACKAGE_PIN D11 [get_ports uart_tx]

############## KEY and LED define#####################
set_property IOSTANDARD LVCMOS33 [get_ports {key[0]}]
set_property PACKAGE_PIN M15 [get_ports {key[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[1]}]
set_property PACKAGE_PIN L15 [get_ports {key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[2]}]
set_property PACKAGE_PIN AB19 [get_ports {key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {key[3]}]
set_property PACKAGE_PIN AA21 [get_ports {key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN H16 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN G16 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN K15 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN J15 [get_ports {led[3]}]
############## CAN define#############################
set_property PACKAGE_PIN T20 [get_ports {can_ad[0]}]
set_property PACKAGE_PIN V20 [get_ports {can_ad[1]}]
set_property PACKAGE_PIN Y21 [get_ports {can_ad[2]}]
set_property PACKAGE_PIN R18 [get_ports {can_ad[3]}]
set_property PACKAGE_PIN R16 [get_ports {can_ad[4]}]
set_property PACKAGE_PIN T17 [get_ports {can_ad[5]}]
set_property PACKAGE_PIN U18 [get_ports {can_ad[6]}]
set_property PACKAGE_PIN V18 [get_ports {can_ad[7]}]

set_property PACKAGE_PIN T19 [get_ports can_rst_n]
set_property PACKAGE_PIN U20 [get_ports can_mode]
set_property PACKAGE_PIN W21 [get_ports can_wr_n]
set_property PACKAGE_PIN P17 [get_ports can_rd_n]
set_property PACKAGE_PIN N15 [get_ports can_cs_n]
set_property PACKAGE_PIN R17 [get_ports can_ale]
set_property PACKAGE_PIN U17 [get_ports can_dir]
set_property PACKAGE_PIN U19 [get_ports can_oe_n]
set_property PACKAGE_PIN V19 [get_ports can_dir_1]
set_property PACKAGE_PIN W22 [get_ports can_oe_n_1]

#set_property PACKAGE_PIN U19 [get_ports can_int_n]

set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {can_ad[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports can_cs_n]
set_property IOSTANDARD LVCMOS33 [get_ports can_ale]
set_property IOSTANDARD LVCMOS33 [get_ports can_wr_n]
set_property IOSTANDARD LVCMOS33 [get_ports can_rd_n]
#set_property IOSTANDARD LVCMOS33 [get_ports can_int_n]
set_property IOSTANDARD LVCMOS33 [get_ports can_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports can_mode]
set_property IOSTANDARD LVCMOS33 [get_ports can_dir]
set_property IOSTANDARD LVCMOS33 [get_ports can_oe_n]
set_property IOSTANDARD LVCMOS33 [get_ports can_dir_1]
set_property IOSTANDARD LVCMOS33 [get_ports can_oe_n_1]

connect_debug_port u_ila_0/probe1 [get_nets [list {dout_32b_o[0]} {dout_32b_o[1]} {dout_32b_o[2]} {dout_32b_o[3]} {dout_32b_o[4]} {dout_32b_o[5]} {dout_32b_o[6]} {dout_32b_o[7]} {dout_32b_o[8]} {dout_32b_o[9]} {dout_32b_o[10]} {dout_32b_o[11]} {dout_32b_o[12]} {dout_32b_o[13]} {dout_32b_o[14]} {dout_32b_o[15]} {dout_32b_o[16]} {dout_32b_o[17]} {dout_32b_o[18]} {dout_32b_o[19]} {dout_32b_o[20]} {dout_32b_o[21]} {dout_32b_o[22]} {dout_32b_o[23]} {dout_32b_o[24]} {dout_32b_o[25]} {dout_32b_o[26]} {dout_32b_o[27]} {dout_32b_o[28]} {dout_32b_o[29]} {dout_32b_o[30]} {dout_32b_o[31]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {num_string[0]} {num_string[1]} {num_string[2]} {num_string[3]} {num_string[4]} {num_string[5]} {num_string[6]} {num_string[7]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {din_32b_i[0]} {din_32b_i[1]} {din_32b_i[2]} {din_32b_i[3]} {din_32b_i[4]} {din_32b_i[5]} {din_32b_i[6]} {din_32b_i[7]} {din_32b_i[8]} {din_32b_i[9]} {din_32b_i[10]} {din_32b_i[11]} {din_32b_i[12]} {din_32b_i[13]} {din_32b_i[14]} {din_32b_i[15]} {din_32b_i[16]} {din_32b_i[17]} {din_32b_i[18]} {din_32b_i[19]} {din_32b_i[20]} {din_32b_i[21]} {din_32b_i[22]} {din_32b_i[23]} {din_32b_i[24]} {din_32b_i[25]} {din_32b_i[26]} {din_32b_i[27]} {din_32b_i[28]} {din_32b_i[29]} {din_32b_i[30]} {din_32b_i[31]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {addr_32b_i[0]} {addr_32b_i[1]} {addr_32b_i[2]} {addr_32b_i[3]} {addr_32b_i[4]} {addr_32b_i[5]} {addr_32b_i[6]} {addr_32b_i[7]} {addr_32b_i[8]} {addr_32b_i[9]} {addr_32b_i[10]} {addr_32b_i[11]} {addr_32b_i[12]} {addr_32b_i[13]} {addr_32b_i[14]} {addr_32b_i[15]} {addr_32b_i[16]} {addr_32b_i[17]} {addr_32b_i[18]} {addr_32b_i[19]} {addr_32b_i[20]} {addr_32b_i[21]} {addr_32b_i[22]} {addr_32b_i[23]} {addr_32b_i[24]} {addr_32b_i[25]} {addr_32b_i[26]} {addr_32b_i[27]} {addr_32b_i[28]} {addr_32b_i[29]} {addr_32b_i[30]} {addr_32b_i[31]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list add_1_str]]
connect_debug_port u_ila_0/probe10 [get_nets [list dout_32b_valid_o]]
connect_debug_port u_ila_0/probe13 [get_nets [list interrupt_o]]
connect_debug_port u_ila_0/probe14 [get_nets [list rden_i]]
connect_debug_port u_ila_0/probe18 [get_nets [list sub_1_str]]
connect_debug_port u_ila_0/probe23 [get_nets [list wren_i]]
connect_debug_port u_ila_1/probe3 [get_nets [list {can_inst/read_inst/temp_preKey_in[0]} {can_inst/read_inst/temp_preKey_in[1]} {can_inst/read_inst/temp_preKey_in[2]} {can_inst/read_inst/temp_preKey_in[3]}]]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_inst/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dout_32b_uart[0]} {dout_32b_uart[1]} {dout_32b_uart[2]} {dout_32b_uart[3]} {dout_32b_uart[4]} {dout_32b_uart[5]} {dout_32b_uart[6]} {dout_32b_uart[7]} {dout_32b_uart[8]} {dout_32b_uart[9]} {dout_32b_uart[10]} {dout_32b_uart[11]} {dout_32b_uart[12]} {dout_32b_uart[13]} {dout_32b_uart[14]} {dout_32b_uart[15]} {dout_32b_uart[16]} {dout_32b_uart[17]} {dout_32b_uart[18]} {dout_32b_uart[19]} {dout_32b_uart[20]} {dout_32b_uart[21]} {dout_32b_uart[22]} {dout_32b_uart[23]} {dout_32b_uart[24]} {dout_32b_uart[25]} {dout_32b_uart[26]} {dout_32b_uart[27]} {dout_32b_uart[28]} {dout_32b_uart[29]} {dout_32b_uart[30]} {dout_32b_uart[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {addr_32b_can[0]} {addr_32b_can[1]} {addr_32b_can[2]} {addr_32b_can[3]} {addr_32b_can[4]} {addr_32b_can[5]} {addr_32b_can[6]} {addr_32b_can[7]} {addr_32b_can[8]} {addr_32b_can[9]} {addr_32b_can[10]} {addr_32b_can[11]} {addr_32b_can[12]} {addr_32b_can[13]} {addr_32b_can[14]} {addr_32b_can[15]} {addr_32b_can[16]} {addr_32b_can[17]} {addr_32b_can[18]} {addr_32b_can[19]} {addr_32b_can[20]} {addr_32b_can[21]} {addr_32b_can[22]} {addr_32b_can[23]} {addr_32b_can[24]} {addr_32b_can[25]} {addr_32b_can[26]} {addr_32b_can[27]} {addr_32b_can[28]} {addr_32b_can[29]} {addr_32b_can[30]} {addr_32b_can[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {addr_32b_uart[0]} {addr_32b_uart[1]} {addr_32b_uart[2]} {addr_32b_uart[3]} {addr_32b_uart[4]} {addr_32b_uart[5]} {addr_32b_uart[6]} {addr_32b_uart[7]} {addr_32b_uart[8]} {addr_32b_uart[9]} {addr_32b_uart[10]} {addr_32b_uart[11]} {addr_32b_uart[12]} {addr_32b_uart[13]} {addr_32b_uart[14]} {addr_32b_uart[15]} {addr_32b_uart[16]} {addr_32b_uart[17]} {addr_32b_uart[18]} {addr_32b_uart[19]} {addr_32b_uart[20]} {addr_32b_uart[21]} {addr_32b_uart[22]} {addr_32b_uart[23]} {addr_32b_uart[24]} {addr_32b_uart[25]} {addr_32b_uart[26]} {addr_32b_uart[27]} {addr_32b_uart[28]} {addr_32b_uart[29]} {addr_32b_uart[30]} {addr_32b_uart[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {din_32b_can[0]} {din_32b_can[1]} {din_32b_can[2]} {din_32b_can[3]} {din_32b_can[4]} {din_32b_can[5]} {din_32b_can[6]} {din_32b_can[7]} {din_32b_can[8]} {din_32b_can[9]} {din_32b_can[10]} {din_32b_can[11]} {din_32b_can[12]} {din_32b_can[13]} {din_32b_can[14]} {din_32b_can[15]} {din_32b_can[16]} {din_32b_can[17]} {din_32b_can[18]} {din_32b_can[19]} {din_32b_can[20]} {din_32b_can[21]} {din_32b_can[22]} {din_32b_can[23]} {din_32b_can[24]} {din_32b_can[25]} {din_32b_can[26]} {din_32b_can[27]} {din_32b_can[28]} {din_32b_can[29]} {din_32b_can[30]} {din_32b_can[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {din_32b_uart[0]} {din_32b_uart[1]} {din_32b_uart[2]} {din_32b_uart[3]} {din_32b_uart[4]} {din_32b_uart[5]} {din_32b_uart[6]} {din_32b_uart[7]} {din_32b_uart[8]} {din_32b_uart[9]} {din_32b_uart[10]} {din_32b_uart[11]} {din_32b_uart[12]} {din_32b_uart[13]} {din_32b_uart[14]} {din_32b_uart[15]} {din_32b_uart[16]} {din_32b_uart[17]} {din_32b_uart[18]} {din_32b_uart[19]} {din_32b_uart[20]} {din_32b_uart[21]} {din_32b_uart[22]} {din_32b_uart[23]} {din_32b_uart[24]} {din_32b_uart[25]} {din_32b_uart[26]} {din_32b_uart[27]} {din_32b_uart[28]} {din_32b_uart[29]} {din_32b_uart[30]} {din_32b_uart[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {uart_inst/uart_ctl/din_tx[0]} {uart_inst/uart_ctl/din_tx[1]} {uart_inst/uart_ctl/din_tx[2]} {uart_inst/uart_ctl/din_tx[3]} {uart_inst/uart_ctl/din_tx[4]} {uart_inst/uart_ctl/din_tx[5]} {uart_inst/uart_ctl/din_tx[6]} {uart_inst/uart_ctl/din_tx[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {conn_can_uart/dout_data_can[0]} {conn_can_uart/dout_data_can[1]} {conn_can_uart/dout_data_can[2]} {conn_can_uart/dout_data_can[3]} {conn_can_uart/dout_data_can[4]} {conn_can_uart/dout_data_can[5]} {conn_can_uart/dout_data_can[6]} {conn_can_uart/dout_data_can[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {conn_can_uart/num_string[0]} {conn_can_uart/num_string[1]} {conn_can_uart/num_string[2]} {conn_can_uart/num_string[3]} {conn_can_uart/num_string[4]} {conn_can_uart/num_string[5]} {conn_can_uart/num_string[6]} {conn_can_uart/num_string[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list conn_can_uart/add_1_str]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list dout_32b_valid_uart]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list interrupt_uart]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list rden_can]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list conn_can_uart/rden_data_can]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list rden_uart]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list conn_can_uart/sub_1_str]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list wren_can]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list wren_uart]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 1 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_inst/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 32 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {addr_32b_can_r[0]} {addr_32b_can_r[1]} {addr_32b_can_r[2]} {addr_32b_can_r[3]} {addr_32b_can_r[4]} {addr_32b_can_r[5]} {addr_32b_can_r[6]} {addr_32b_can_r[7]} {addr_32b_can_r[8]} {addr_32b_can_r[9]} {addr_32b_can_r[10]} {addr_32b_can_r[11]} {addr_32b_can_r[12]} {addr_32b_can_r[13]} {addr_32b_can_r[14]} {addr_32b_can_r[15]} {addr_32b_can_r[16]} {addr_32b_can_r[17]} {addr_32b_can_r[18]} {addr_32b_can_r[19]} {addr_32b_can_r[20]} {addr_32b_can_r[21]} {addr_32b_can_r[22]} {addr_32b_can_r[23]} {addr_32b_can_r[24]} {addr_32b_can_r[25]} {addr_32b_can_r[26]} {addr_32b_can_r[27]} {addr_32b_can_r[28]} {addr_32b_can_r[29]} {addr_32b_can_r[30]} {addr_32b_can_r[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 32 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {din_32b_can_r[0]} {din_32b_can_r[1]} {din_32b_can_r[2]} {din_32b_can_r[3]} {din_32b_can_r[4]} {din_32b_can_r[5]} {din_32b_can_r[6]} {din_32b_can_r[7]} {din_32b_can_r[8]} {din_32b_can_r[9]} {din_32b_can_r[10]} {din_32b_can_r[11]} {din_32b_can_r[12]} {din_32b_can_r[13]} {din_32b_can_r[14]} {din_32b_can_r[15]} {din_32b_can_r[16]} {din_32b_can_r[17]} {din_32b_can_r[18]} {din_32b_can_r[19]} {din_32b_can_r[20]} {din_32b_can_r[21]} {din_32b_can_r[22]} {din_32b_can_r[23]} {din_32b_can_r[24]} {din_32b_can_r[25]} {din_32b_can_r[26]} {din_32b_can_r[27]} {din_32b_can_r[28]} {din_32b_can_r[29]} {din_32b_can_r[30]} {din_32b_can_r[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 32 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {dout_32b_can[0]} {dout_32b_can[1]} {dout_32b_can[2]} {dout_32b_can[3]} {dout_32b_can[4]} {dout_32b_can[5]} {dout_32b_can[6]} {dout_32b_can[7]} {dout_32b_can[8]} {dout_32b_can[9]} {dout_32b_can[10]} {dout_32b_can[11]} {dout_32b_can[12]} {dout_32b_can[13]} {dout_32b_can[14]} {dout_32b_can[15]} {dout_32b_can[16]} {dout_32b_can[17]} {dout_32b_can[18]} {dout_32b_can[19]} {dout_32b_can[20]} {dout_32b_can[21]} {dout_32b_can[22]} {dout_32b_can[23]} {dout_32b_can[24]} {dout_32b_can[25]} {dout_32b_can[26]} {dout_32b_can[27]} {dout_32b_can[28]} {dout_32b_can[29]} {dout_32b_can[30]} {dout_32b_can[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 8 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {can_inst/read_inst/can_ad_o[0]} {can_inst/read_inst/can_ad_o[1]} {can_inst/read_inst/can_ad_o[2]} {can_inst/read_inst/can_ad_o[3]} {can_inst/read_inst/can_ad_o[4]} {can_inst/read_inst/can_ad_o[5]} {can_inst/read_inst/can_ad_o[6]} {can_inst/read_inst/can_ad_o[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 4 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {can_inst/read_inst/state_can[0]} {can_inst/read_inst/state_can[1]} {can_inst/read_inst/state_can[2]} {can_inst/read_inst/state_can[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 8 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {can_inst/read_inst/data_reg[0]} {can_inst/read_inst/data_reg[1]} {can_inst/read_inst/data_reg[2]} {can_inst/read_inst/data_reg[3]} {can_inst/read_inst/data_reg[4]} {can_inst/read_inst/data_reg[5]} {can_inst/read_inst/data_reg[6]} {can_inst/read_inst/data_reg[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 8 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {can_inst/read_inst/data_rd[0]} {can_inst/read_inst/data_rd[1]} {can_inst/read_inst/data_rd[2]} {can_inst/read_inst/data_rd[3]} {can_inst/read_inst/data_rd[4]} {can_inst/read_inst/data_rd[5]} {can_inst/read_inst/data_rd[6]} {can_inst/read_inst/data_rd[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list can_inst/read_inst/can_ad_sel]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list can_inst/read_inst/can_ale]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe9]
set_property port_width 1 [get_debug_ports u_ila_1/probe9]
connect_debug_port u_ila_1/probe9 [get_nets [list can_inst/read_inst/can_cs_n]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe10]
set_property port_width 1 [get_debug_ports u_ila_1/probe10]
connect_debug_port u_ila_1/probe10 [get_nets [list can_inst/read_inst/can_rd_n]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe11]
set_property port_width 1 [get_debug_ports u_ila_1/probe11]
connect_debug_port u_ila_1/probe11 [get_nets [list can_inst/read_inst/can_rst_n]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe12]
set_property port_width 1 [get_debug_ports u_ila_1/probe12]
connect_debug_port u_ila_1/probe12 [get_nets [list can_inst/read_inst/can_wr_n]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe13]
set_property port_width 1 [get_debug_ports u_ila_1/probe13]
connect_debug_port u_ila_1/probe13 [get_nets [list dout_32b_valid_can]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe14]
set_property port_width 1 [get_debug_ports u_ila_1/probe14]
connect_debug_port u_ila_1/probe14 [get_nets [list rden_can_r]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe15]
set_property port_width 1 [get_debug_ports u_ila_1/probe15]
connect_debug_port u_ila_1/probe15 [get_nets [list wren_can_r]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_125MHz]
